//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGenealogy.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartGenealogy.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Action_Continue {
            get {
                return ResourceManager.GetString("Action_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re checking some hardware specifications to determine compatibility..
        /// </summary>
        public static string Label_CheckingHardware {
            get {
                return ResourceManager.GetString("Label_CheckingHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Directory.
        /// </summary>
        public static string Label_DataDirectory {
            get {
                return ResourceManager.GetString("Label_DataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where application data (model checkpoints, web UIs, etc.) will be installed..
        /// </summary>
        public static string Label_DataDirectoryExplanation {
            get {
                return ResourceManager.GetString("Label_DataDirectoryExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything looks good!.
        /// </summary>
        public static string Label_EverythingLooksGood {
            get {
                return ResourceManager.GetString("Label_EverythingLooksGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may encounter errors when using a FAT32 or exFAT drive. Select a different drive for a smoother experience..
        /// </summary>
        public static string Label_FatWarning {
            get {
                return ResourceManager.GetString("Label_FatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started.
        /// </summary>
        public static string Label_LetsGetStarted {
            get {
                return ResourceManager.GetString("Label_LetsGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We recommend a GPU with CUDA support for the best experience. You can continue without one, but some packages may not work, and inference may be slower..
        /// </summary>
        public static string Label_NvidiaGpuRecommended {
            get {
                return ResourceManager.GetString("Label_NvidiaGpuRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Data Directory.
        /// </summary>
        public static string Label_PleaseSelectDataDirectory {
            get {
                return ResourceManager.GetString("Label_PleaseSelectDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Mode.
        /// </summary>
        public static string Label_PortableMode {
            get {
                return ResourceManager.GetString("Label_PortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Portable Mode, all data and settings will be stored in the same directory as the application. You will be able to move the application with its &apos;Data&apos; folder to a different location or computer..
        /// </summary>
        public static string Label_PortableModeExplanation {
            get {
                return ResourceManager.GetString("Label_PortableModeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Smart Genealogy!.
        /// </summary>
        public static string Text_WelcomeToSmartGenealogy {
            get {
                return ResourceManager.GetString("Text_WelcomeToSmartGenealogy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE EXTRACT THE APP FROM THE ZIP FILE BEFORE RUNNING SMART GENEALOGY.
        /// </summary>
        public static string Warning_PleaseExtractFirst {
            get {
                return ResourceManager.GetString("Warning_PleaseExtractFirst", resourceCulture);
            }
        }
    }
}
