//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGenealogy.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartGenealogy.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add for All Users.
        /// </summary>
        public static string Action_AddForAllUsers {
            get {
                return ResourceManager.GetString("Action_AddForAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add for Current User.
        /// </summary>
        public static string Action_AddForCurrentUser {
            get {
                return ResourceManager.GetString("Action_AddForCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Action_Close {
            get {
                return ResourceManager.GetString("Action_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Action_Continue {
            get {
                return ResourceManager.GetString("Action_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Now.
        /// </summary>
        public static string Action_InstallNow {
            get {
                return ResourceManager.GetString("Action_InstallNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Action_Quit {
            get {
                return ResourceManager.GetString("Action_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch.
        /// </summary>
        public static string Action_Relaunch {
            get {
                return ResourceManager.GetString("Action_Relaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch Later.
        /// </summary>
        public static string Action_RelaunchLater {
            get {
                return ResourceManager.GetString("Action_RelaunchLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Me Later.
        /// </summary>
        public static string Action_RemindMeLater {
            get {
                return ResourceManager.GetString("Action_RemindMeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Action_Restart {
            get {
                return ResourceManager.GetString("Action_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Directory.
        /// </summary>
        public static string Action_SelectDirectory {
            get {
                return ResourceManager.GetString("Action_SelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Label_About {
            get {
                return ResourceManager.GetString("Label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Smart Genealogy to the Start Menu.
        /// </summary>
        public static string Label_AddToStartMenu {
            get {
                return ResourceManager.GetString("Label_AddToStartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses the current app location, you can run this again if you move the app.
        /// </summary>
        public static string Label_AddToStartMenu_Details {
            get {
                return ResourceManager.GetString("Label_AddToStartMenu_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Label_Appearance {
            get {
                return ResourceManager.GetString("Label_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes Applied.
        /// </summary>
        public static string Label_ChangesApplied {
            get {
                return ResourceManager.GetString("Label_ChangesApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re checking some hardware specifications to determine compatibility..
        /// </summary>
        public static string Label_CheckingHardware {
            get {
                return ResourceManager.GetString("Label_CheckingHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current directory:.
        /// </summary>
        public static string Label_CurrentDirectory {
            get {
                return ResourceManager.GetString("Label_CurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Directory.
        /// </summary>
        public static string Label_DataDirectory {
            get {
                return ResourceManager.GetString("Label_DataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where application data (model checkpoints, web UIs, etc.) will be installed..
        /// </summary>
        public static string Label_DataDirectoryExplanation {
            get {
                return ResourceManager.GetString("Label_DataDirectoryExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything looks good!.
        /// </summary>
        public static string Label_EverythingLooksGood {
            get {
                return ResourceManager.GetString("Label_EverythingLooksGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may encounter errors when using a FAT32 or exFAT drive. Select a different drive for a smoother experience..
        /// </summary>
        public static string Label_FatWarning {
            get {
                return ResourceManager.GetString("Label_FatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Label_General {
            get {
                return ResourceManager.GetString("Label_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Label_Home {
            get {
                return ResourceManager.GetString("Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started.
        /// </summary>
        public static string Label_LetsGetStarted {
            get {
                return ResourceManager.GetString("Label_LetsGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Agreement..
        /// </summary>
        public static string Label_LicenseAgreement {
            get {
                return ResourceManager.GetString("Label_LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Smart Genealogy is available!.
        /// </summary>
        public static string Label_NewVersionAvailable {
            get {
                return ResourceManager.GetString("Label_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We recommend a GPU with CUDA support for the best experience. You can continue without one, but some packages may not work, and inference may be slower..
        /// </summary>
        public static string Label_NvidiaGpuRecommended {
            get {
                return ResourceManager.GetString("Label_NvidiaGpuRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only available on Windows.
        /// </summary>
        public static string Label_OnlyAvailableOnWindows {
            get {
                return ResourceManager.GetString("Label_OnlyAvailableOnWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Data Directory.
        /// </summary>
        public static string Label_PleaseSelectDataDirectory {
            get {
                return ResourceManager.GetString("Label_PleaseSelectDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Mode.
        /// </summary>
        public static string Label_PortableMode {
            get {
                return ResourceManager.GetString("Label_PortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Portable Mode, all data and settings will be stored in the same directory as the application. You will be able to move the application with its &apos;Data&apos; folder to a different location or computer..
        /// </summary>
        public static string Label_PortableModeExplanation {
            get {
                return ResourceManager.GetString("Label_PortableModeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agree to the.
        /// </summary>
        public static string Label_ReadAndAgree {
            get {
                return ResourceManager.GetString("Label_ReadAndAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch Required.
        /// </summary>
        public static string Label_RelaunchRequired {
            get {
                return ResourceManager.GetString("Label_RelaunchRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        public static string Label_ReleaseNotes {
            get {
                return ResourceManager.GetString("Label_ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        public static string Label_RestartRequired {
            get {
                return ResourceManager.GetString("Label_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new Data Directory.
        /// </summary>
        public static string Label_SelectNewDataDirectory {
            get {
                return ResourceManager.GetString("Label_SelectNewDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not move existing data.
        /// </summary>
        public static string Label_SelectNewDataDirectory_Details {
            get {
                return ResourceManager.GetString("Label_SelectNewDataDirectory_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Genealogy.
        /// </summary>
        public static string Label_SmartGenealogy {
            get {
                return ResourceManager.GetString("Label_SmartGenealogy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Label_System {
            get {
                return ResourceManager.GetString("Label_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Label_Theme {
            get {
                return ResourceManager.GetString("Label_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string Label_UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("Label_UnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string Label_UpdateAvailable {
            get {
                return ResourceManager.GetString("Label_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app will relaunch after updating.
        /// </summary>
        public static string Text_AppWillRelaunchAfterUpdate {
            get {
                return ResourceManager.GetString("Text_AppWillRelaunchAfterUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch is required for new language option to take effect.
        /// </summary>
        public static string Text_RelaunchRequiredToApplyLanguage {
            get {
                return ResourceManager.GetString("Text_RelaunchRequiredToApplyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A restart may be required for system changes to take effect..
        /// </summary>
        public static string Text_RestartMayBeRequiredForSystemChanges {
            get {
                return ResourceManager.GetString("Text_RestartMayBeRequiredForSystemChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Genealogy must be restarted for the changes to take effect..
        /// </summary>
        public static string Text_RestartRequired {
            get {
                return ResourceManager.GetString("Text_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Smart Genealogy!.
        /// </summary>
        public static string Text_WelcomeToSmartGenealogy {
            get {
                return ResourceManager.GetString("Text_WelcomeToSmartGenealogy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}.
        /// </summary>
        public static string TextTemplate_UpdatingPackage {
            get {
                return ResourceManager.GetString("TextTemplate_UpdatingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE EXTRACT THE APP FROM THE ZIP FILE BEFORE RUNNING SMART GENEALOGY.
        /// </summary>
        public static string Warning_PleaseExtractFirst {
            get {
                return ResourceManager.GetString("Warning_PleaseExtractFirst", resourceCulture);
            }
        }
    }
}
