//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGenealogy.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartGenealogy.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Action_Continue {
            get {
                return ResourceManager.GetString("Action_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch.
        /// </summary>
        public static string Action_Relaunch {
            get {
                return ResourceManager.GetString("Action_Relaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch Later.
        /// </summary>
        public static string Action_RelaunchLater {
            get {
                return ResourceManager.GetString("Action_RelaunchLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Action_Restart {
            get {
                return ResourceManager.GetString("Action_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Directory.
        /// </summary>
        public static string Action_SelectDirectory {
            get {
                return ResourceManager.GetString("Action_SelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Label_About {
            get {
                return ResourceManager.GetString("Label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Label_Appearance {
            get {
                return ResourceManager.GetString("Label_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current directory:.
        /// </summary>
        public static string Label_CurrentDirectory {
            get {
                return ResourceManager.GetString("Label_CurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Directory.
        /// </summary>
        public static string Label_DataDirectory {
            get {
                return ResourceManager.GetString("Label_DataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where application data (model checkpoints, web UIs, etc.) will be installed..
        /// </summary>
        public static string Label_DataDirectoryExplanation {
            get {
                return ResourceManager.GetString("Label_DataDirectoryExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may encounter errors when using a FAT32 or exFAT drive. Select a different drive for a smoother experience..
        /// </summary>
        public static string Label_FatWarning {
            get {
                return ResourceManager.GetString("Label_FatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Format.
        /// </summary>
        public static string Label_NumberFormat {
            get {
                return ResourceManager.GetString("Label_NumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Data Directory.
        /// </summary>
        public static string Label_PleaseSelectDataDirectory {
            get {
                return ResourceManager.GetString("Label_PleaseSelectDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch Required.
        /// </summary>
        public static string Label_RelaunchRequired {
            get {
                return ResourceManager.GetString("Label_RelaunchRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        public static string Label_RestartRequired {
            get {
                return ResourceManager.GetString("Label_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new Data Directory.
        /// </summary>
        public static string Label_SelectNewDataDirectory {
            get {
                return ResourceManager.GetString("Label_SelectNewDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not move existing data. Requires application restart..
        /// </summary>
        public static string Label_SelectNewDataDirectory_Details {
            get {
                return ResourceManager.GetString("Label_SelectNewDataDirectory_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Genealogy.
        /// </summary>
        public static string Label_SmartGenealogy {
            get {
                return ResourceManager.GetString("Label_SmartGenealogy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Label_System {
            get {
                return ResourceManager.GetString("Label_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Label_Theme {
            get {
                return ResourceManager.GetString("Label_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch is required for new language option to take effect.
        /// </summary>
        public static string Text_RelaunchRequiredToApplyLanguage {
            get {
                return ResourceManager.GetString("Text_RelaunchRequiredToApplyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Genealogy must be restarted for the changes to take effect..
        /// </summary>
        public static string Text_RestartRequired {
            get {
                return ResourceManager.GetString("Text_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Smart Genealogy!.
        /// </summary>
        public static string Text_WelcomeToSmartGenealogy {
            get {
                return ResourceManager.GetString("Text_WelcomeToSmartGenealogy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE EXTRACT THE APP FROM THE ZIP FILE BEFORE RUNNING SMART GENEALOGY.
        /// </summary>
        public static string Warning_PleaseExtractFirst {
            get {
                return ResourceManager.GetString("Warning_PleaseExtractFirst", resourceCulture);
            }
        }
    }
}
