//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGenealogy.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartGenealogy.Resources.Translations.AppTranslations", typeof(AppTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Options.
        /// </summary>
        internal static string LabelAccountOptions {
            get {
                return ResourceManager.GetString("LabelAccountOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Settings.
        /// </summary>
        internal static string LabelAISettings {
            get {
                return ResourceManager.GetString("LabelAISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LabelAppLanguage {
            get {
                return ResourceManager.GetString("LabelAppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        internal static string LabelAppSettings {
            get {
                return ResourceManager.GetString("LabelAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string LabelArticle {
            get {
                return ResourceManager.GetString("LabelArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AW Web Solutions.
        /// </summary>
        internal static string LabelAWWebSolutions {
            get {
                return ResourceManager.GetString("LabelAWWebSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string LabelClear {
            get {
                return ResourceManager.GetString("LabelClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string LabelConfirm {
            get {
                return ResourceManager.GetString("LabelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        internal static string LabelDarkmode {
            get {
                return ResourceManager.GetString("LabelDarkmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a Tree.
        /// </summary>
        internal static string LabelDownloadTree {
            get {
                return ResourceManager.GetString("LabelDownloadTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download data from an online service.
        /// </summary>
        internal static string LabelDownloadTreeDescription {
            get {
                return ResourceManager.GetString("LabelDownloadTreeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string LabelEmpty {
            get {
                return ResourceManager.GetString("LabelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string LabelGoback {
            get {
                return ResourceManager.GetString("LabelGoback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import File.
        /// </summary>
        internal static string LabelImportFile {
            get {
                return ResourceManager.GetString("LabelImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import File from another program.
        /// </summary>
        internal static string LabelImportFileDescription {
            get {
                return ResourceManager.GetString("LabelImportFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        internal static string LabelNewFile {
            get {
                return ResourceManager.GetString("LabelNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new file.
        /// </summary>
        internal static string LabelNewFileDescription {
            get {
                return ResourceManager.GetString("LabelNewFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LabelOk {
            get {
                return ResourceManager.GetString("LabelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint Settings.
        /// </summary>
        internal static string LabelOllamaEndpointSettings {
            get {
                return ResourceManager.GetString("LabelOllamaEndpointSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string LabelOllamaIsRunning {
            get {
                return ResourceManager.GetString("LabelOllamaIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local models.
        /// </summary>
        internal static string LabelOllamaLocalModels {
            get {
                return ResourceManager.GetString("LabelOllamaLocalModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ollama Path.
        /// </summary>
        internal static string LabelOllamaPath {
            get {
                return ResourceManager.GetString("LabelOllamaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ollama Settings.
        /// </summary>
        internal static string LabelOllamaSettings {
            get {
                return ResourceManager.GetString("LabelOllamaSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string LabelOpenFile {
            get {
                return ResourceManager.GetString("LabelOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Smart Genealogy file.
        /// </summary>
        internal static string LabelOpenFileDescription {
            get {
                return ResourceManager.GetString("LabelOpenFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string LabelReset {
            get {
                return ResourceManager.GetString("LabelReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Color.
        /// </summary>
        internal static string LabelSelectAColor {
            get {
                return ResourceManager.GetString("LabelSelectAColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string LabelSelectLanguage {
            get {
                return ResourceManager.GetString("LabelSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Genealogy.
        /// </summary>
        internal static string LabelSmartGenealogy {
            get {
                return ResourceManager.GetString("LabelSmartGenealogy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string MenuArticles {
            get {
                return ResourceManager.GetString("MenuArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ollama Settings.
        /// </summary>
        internal static string PageTitleOllamaSettings {
            get {
                return ResourceManager.GetString("PageTitleOllamaSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Genealogy.
        /// </summary>
        internal static string StringCopyright {
            get {
                return ResourceManager.GetString("StringCopyright", resourceCulture);
            }
        }
    }
}
